# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
parameters:
  APP_BRANCH:
    type: string
    default: "master"
  DEPLOY_ONLY:
    type: boolean
    default: false
  ENABLE_DEPLOYMENT:
    type: boolean
    default: false
  INFRA_AWS_BRANCH:
    type: string
    default: "master"
  STAGE:
    type: string
    default: api
  TARGET_ENV:
    type: string
    default: "ce1"
  TARGET_PROJECT:
    type: string
    default: "specialist-api"
  MIGRATION_TASK_ACTIONS:
    type: string
    default: ""

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - run: "hello george"
